const link = document.getElementById("translate-button");

const burgerLanguageButton = document.getElementById('li-language');

let language = localStorage.getItem("currentLanguage") || "en";

link.addEventListener("click", function (event) {
    event.preventDefault();
    language = language === "en" ? "ru" : "en";

    translate();
});

burgerLanguageButton.addEventListener("click", function (event) {
    event.preventDefault();
    console.log("click")
    language = language === "en" ? "ru" : "en";

    translate();
});

function translate() {
    localStorage.setItem("currentLanguage", language);

    const elements = document.querySelectorAll("[data-i18n]");

    elements.forEach((element) => {
        const translationKey = element.dataset.i18n;

        if (i18n.hasOwnProperty(language) && i18n[language].hasOwnProperty(translationKey)) {
            element.textContent = i18n[language][translationKey];
        }
    });

    document.getElementById("need").placeholder = i18n[language]["need"];
    document.getElementById("email-input").placeholder = i18n[language]["email-input"];
}

const i18n = {
    en: {
        "address": "Address: 60-49 road 11378 new york",
        "bananas": "Fresh Bananas",
        "banner-button": "SHOP NOW",
        "banner-category": "FRUIT FRESH",
        "banner-description": "Free Pickup and Delivery Available",
        "berries": "Fresh Berries",
        "birthDate": "Birth Date*",
        "blog-date": "May 4,2021",
        "blog-text-1": "Busting Salad Myths: Eat a Well-Built Salad (If You Want To)",
        "blog-text-3":
            "This is usually said when someone is trying to lose weight or be “super healthy.” First, to lose weight, it is widely understood that we must burn more calories than we eat.",
        "blog-text-4": "Vitamin C: how much and which sources are best for boosting immunity?",
        "blog-text-7": "Pump Up the Produce Power in Winter Meals",
        "blog-text-9":
            "We’ve all been here before: When it seems the long, gray winter will never end and you make one more pot of hearty vegetable soup or another casserole.",
        "blog-text-10":
            "During cold and flu season, we try to do all we can to prevent illness or speed up how fast we recover from illness. One such strategy many employ is the use of Vitamin C for a natural remedy.",
        "butter": "Butter & Eggs",
        "card-name-1": "Bunch of bananas",
        "card-name-2": "Fresh organic apricot",
        "card-name-3": "Avokado fruit",
        "card-name-4": "Red apple",
        "card-name-5": "Two fresh figs",
        "card-name-6": "Cucumber",
        "card-name-7": "Beef steak",
        "card-name-8": "Raw Broccoli",
        "categories": "All Categories",
        "confirmPassword": "Confirm Password*",
        "crisps": "Papayaya & Crisps",
        "departments": "All Department",
        "dried-fruit": "DRIED FRUIT",
        "dried-fruits": "dried & drink",
        "dried-fruits-2": "fruits",
        "drink-fruits": "DRINK FRUITS",
        "email": "Email",
        "email-input": "Enter Email Address",
        "fastfood": "Fastfood",
        "firstName": "First Name*",
        "fresh-fruit": "FRESH FRUIT",
        "from-blog-header": "From The Blog",
        "fruit": "Fruit & Nut Gifts",
        "li-language": "Switch Language",
        "language": "English",
        "lastName": "Last Name*",
        "link-1": "About us",
        "link-2": "About our shop",
        "link-3": "Secure shopping",
        "link-4": "Delivery infomation",
        "link-5": "Privacy policy",
        "link-6": "Our sitemap",
        "link-blog": "BLOG",
        "link-contact": "CONTACT",
        "link-home": "HOME",
        "link-pages": "PAGES",
        "link-shop": "SHOP",
        "links-header": "useful link",
        "login": "Login",
        "logout": "Logout",
        "meat": "Fresh Meat",
        "natural-juice": "100% all natural fruit juice",
        "newsletter-text-1": "Sign up for our newsletter",
        "newsletter-text-2": "get e-mail updates about our latest shop and special offers.",
        "oatmeal": "Oatmeal",
        "ocean": "Ocean Foods",
        "onion": "Fresh Onion",
        "organic": "Vegetable",
        "organic-2": "100% Organic",
        "password": "Password",
        "patronymic": "Patronymic (optional)",
        "phone": "Phone: +65 11.188.888",
        "product-name-1": "Cauliflower",
        "product-name-2": "Organic quince",
        "product-name-3": "Tomato Hybrid",
        "product-name-4": "Blueberry",
        "product-name-5": "Capsicum-Green",
        "product-name-7": "Hazelnuts Filbert Nut",
        "product-name-8": "Green Apple",
        "product-name-9": "Fresh Raspberry",
        "profile": "Profile",
        "register": "Register",
        "registration-email": "Email*",
        "registration-phone": "Phone Number*",
        "registration-password": "Password*",
        "search": "SEARCH",
        "section-link-1": "Who We Are",
        "section-link-2": "Our Services",
        "section-link-3": "Projects",
        "section-link-4": "Contact",
        "section-link-5": "Innovation",
        "section-link-6": "Testimonials",
        "shipping": "Free Shipping for all order of $99",
        "subscribe-button": "SUBSCRIBE",
        "summer fruits": "summer fruits",
        "support": "support 24/7 time",
        "terms": "I agree to the terms of service",
        "trend-name": "Latest Product",
        "trend-name-2": "Top rated Products",
        "trend-name-3": "Review Products",
        "types-1": "All",
        "types-2": "Oranges",
        "user-profile": "User Profile",
        "vegetables": "Vegetables",
        "vegetables-category": "VEGETABLES",
        "need": "What do you need?",
        "theme-button": "Switch Theme",
        "First Name": "First Name:",
        "Last Name":"Last Name:",
        "Patronymic":"Patronymic:",
        "Phone Number":"Phone Number:",
        "Birth Date":"Birth Date:",
        "Email Address":"Email Address:",
        "Password":"Password:",
        "Role":"Role:",
        "general-info-page-btn": "Go to Info Page",
        "back-to-main-page-btn": "Back to Main Page",
        "general-info-header-customer": "Customer Information",
        "general-info-p1-customer":"Welcome to the Customer Info page!",
        "general-info-p2-customer":"Here, customers can view details and updates specific to their account.",
        "general-info-header-seller": "Seller Information",
        "general-info-p1-seller":"Welcome to the Seller Info page!",
        "general-info-p2-seller":"Here, sellers can manage their products and view sales performance.",
        "back-to-profile-btn":"Back to Profile",
    },
    ru: {
        "address": "Адрес: 60-49 дорога 11378 Нью-Йорк",
        "bananas": "Свежие бананы",
        "banner-button": "КУПИТЬ",
        "banner-category": "СВЕЖИЕ ФРУКТЫ",
        "banner-description": "Доступен бесплатный самовывоз и доставка",
        "berries": "Свежие ягоды",
        "birthDate": "Дата рождения*",
        "blog-date": "4 мая 2021 года",
        "blog-text-1": "Разрушение мифов о салате: ешьте хорошо приготовленный салат (если хотите)",
        "blog-text-3":
            "Это обычно говорят, когда кто-то пытается похудеть или быть «супер здоровым». Во-первых, чтобы похудеть, широко известно, что мы должны сжигать больше калорий, чем потребляем.",
        "blog-text-4": "Витамин С: сколько и какие источники лучше всего подходят для повышения иммунитета?",
        "blog-text-7": "Увеличьте мощность продуктов в зимних блюдах",
        "blog-text-9":
            "Мы все были здесь раньше: когда кажется, что длинная, серая зима никогда не закончится, и вы готовите еще один горшок сытного овощного супа или еще одну запеканку.",
        "blog-text-10":
            "В сезон простуды и гриппа мы стараемся сделать все возможное, чтобы предотвратить заболевание или ускорить выздоровление. Одной из таких стратегий является использование витамина С в качестве натурального средства.",
        "butter": "Масло и яйца",
        "card-name-1": "Бананы",
        "card-name-2": "Свежие абрикосы",
        "card-name-3": "Авокадо",
        "card-name-4": "Красное яблоко",
        "card-name-5": "Свежий инжир",
        "card-name-6": "Огурец",
        "card-name-7": "Говяжий стейк",
        "card-name-8": "Брокколи",
        "categories": "Все категории",
        "confirmPassword": "Повторите пароль*",
        "crisps": "Папайя и чипсы",
        "departments": "Все отделы",
        "dried-fruit": "СУШЕНЫЕ ФРУКТЫ",
        "dried-fruits": "фруктовые",
        "dried-fruits-2": "напитки",
        "drink-fruits": "НАПИТКИ",
        "email": "Эл. почта",
        "email-input": "Адрес эл.почты",
        "fastfood": "Фастфуд",
        "firstName": "Имя*",
        "fresh-fruit": "СВЕЖИЕ ФРУКТЫ",
        "from-blog-header": "Из блога",
        "fruit": "Фрукты и орехи",
        "li-language": "Сменить язык",
        "language": "Русский",
        "lastName": "Фамилия*",
        "link-1": "О нас",
        "link-2": "О нашем магазине",
        "link-3": "Безопасные покупки",
        "link-4": "Информация о доставке",
        "link-5": "Политика конфиденциальности",
        "link-6": "Карта сайта",
        "link-blog": "БЛОГ",
        "link-contact": "КОНТАКТЫ",
        "link-home": "ГЛАВНАЯ",
        "link-pages": "СТРАНИЦЫ",
        "link-shop": "МАГАЗИН",
        "links-header": "ссылки",
        "login": "Войти",
        "logout": "Выйти",
        "meat": "Свежее мясо",
        "natural-juice": "100% натуральный фруктовый сок",
        "newsletter-text-1": "Подпишитесь на нашу рассылку",
        "newsletter-text-2": "получайте обновления по электронной почте о нашем магазине и специальных предложениях.",
        "oatmeal": "Овсянка",
        "ocean": "Морепродукты",
        "onion": "Свежий лук",
        "organic": "Овощи",
        "organic-2": "100% органические",
        "password": "Пароль",
        "patronymic": "Отчество (опционально)",
        "phone": "Телефон: +65 11.188.888",
        "product-name-1": "Цветная капуста",
        "product-name-2": "Органическая айва",
        "product-name-3": "Гибридный томат",
        "product-name-4": "Черника",
        "product-name-5": "Зеленый перец",
        "product-name-7": "Фундук",
        "product-name-8": "Зеленое яблоко",
        "product-name-9": "Свежая малина",
        "profile": "Профиль",
        "register": "Регистрация",
        "registration-email": "Эл. почта*",
        "registration-phone": "Номер телефона*",
        "registration-password": "Пароль*",
        "search": "ПОИСК",
        "section-link-1": "Кто мы",
        "section-link-2": "Наши услуги",
        "section-link-3": "Проекты",
        "section-link-4": "Контакты",
        "section-link-5": "Инновации",
        "section-link-6": "Отзывы",
        "shipping": "Бесплатная доставка от $99",
        "subscribe-button": "ПОДПИСАТЬСЯ",
        "summer fruits": "летние фрукты",
        "support": "поддержка 24/7",
        "terms": "Я согласен с условиями сервиса",
        "trend-name": "Последние продукты",
        "trend-name-2": "Топ продукты",
        "trend-name-3": "Продукты с отзывами",
        "types-1": "Все",
        "types-2": "Апельсины",
        "user-profile": "Ваш профиль",
        "vegetables": "Овощи",
        "vegetables-category": "ОВОЩИ",
        "need": "Что вас интересует?",
        "theme-button": "Сменить тему",
        "First Name": "Имя:",
        "Last Name":"Фамилия:",
        "Patronymic":"Отчество:",
        "Phone Number":"Номер телефона:",
        "Birth Date":"Дата рождения:",
        "Email Address":"Адрес эл. почты:",
        "Password":"Пароль:",
        "Role":"Роль:",
        "general-info-page-btn": "На страницу информации",
        "back-to-main-page-btn": "На главную страницу",
        "general-info-header-customer": "Информация для клиентов",
        "general-info-p1-customer":"Добро пожаловать на страницу информации для клиентов!",
        "general-info-p2-customer":"Здесь клиенты могут просматривать подробную информацию и обновления, касающиеся их учетной записи.",
        "general-info-header-seller": "Информация для продавцов",
        "general-info-p1-seller":"Добро пожаловать на страницу информации для продавцов!",
        "general-info-p2-seller":"Здесь продавцы могут управлять своими товарами и просматривать показатели продаж.",
        "back-to-profile-btn":"На страницу профиля",
    }
};

if (language === "ru") {
    translate();
}
